### ISSUE TITLE
CSC369 takedown notice

### ISSUE THREAD

**Issue by bogdansimion** [Edwardlzy/CSC369#1]
According to the CSC369 course policy you are not to post solutions publicly on Github or anywhere else, regardless whether the course is over. Please make your repository private.

**Comment by lifeisrage** [comment]
stfu bitch mans need to pass

**Comment by bogdansimion** [comment]
This is a note for this student to be aware of this matter. We have all submission on file anyway, and these will be checked against any other present or future submissions. Should plagiarism occur, this will become a matter for the Academic Integrity Coordinator and the Dean's office. Have a nice day.
